version: '3'
services:
  web:
    # image: fpfis/httpd-php-dev:7.1
    image: fpfis/httpd-php-dev:5.6
    working_dir: ${PWD}
    volumes:
      - ${PWD}:${PWD}
      - ${PWD}/my.conf:/etc/apache2/conf-enabled/my.conf
    environment:
      XDEBUG_CONFIG: "idekey=cloud9ide remote_connect_back=0 remote_host=${DOCKER_HOST_IP} remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Test"
      DOCUMENT_ROOT: "${PWD}/build"
      VIRTUAL_HOST: "http://web:8080/"
  
  mysql:
    image: percona/percona-server:5.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'drupal'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'dbpass'
  volumes:
      - 'mysql-data:/var/lib/mysql'
  
  selenium:
    image: wernight/phantomjs
    ports:
      - 8910:8910
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
    command: "phantomjs --webdriver=8910 --ignore-ssl-errors=true --ssl-protocol=any"

volumes:
  mysql-data: null